name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

env:
  REGISTRY: forgejo.kalmonipa.net
  IMAGE_NAME: ${{ github.repository }}
  DOCKER_HOST: tcp://dind:2375

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    container:
      image: catthehacker/ubuntu:act-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Verify Docker connection
        run: |
          echo "Docker host: $DOCKER_HOST"
          docker version
          docker info
      
      - name: Log in to Container Registry
        run: |
          echo "${{ secrets.FORGEJO_TOKEN }}" | docker login ${{ env.REGISTRY }} -u "${{ secrets.REGISTRY_USERNAME }}" --password-stdin
      
      - name: Build Docker image
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest .
          docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} .
      
      - name: Push Docker image
        run: |
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
