name: Build and Push Docker Image

on:
  push:
    tags:
      - v*.*.*

env:
  REGISTRY: forgejo.kalmonipa.net
  IMAGE_NAME: kalmonipa/arty
  DOCKER_HOST: tcp://dind:2375
  API_TOKEN: some-test-token
  CHARACTER_NAME: some-character
  ROLE: some-role

jobs:
  build-and-push:
    runs-on: docker
    container:
      image: catthehacker/ubuntu:act-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      # - name: Run tests
      #   run: |
      #     npm ci
      #     npm run build
      #     npm run test
      - name: Verify Docker connection
        run: |
          echo "Docker host: $DOCKER_HOST"
          docker version
          docker info
      - name: Log in to Container Registry
        run: |
          echo "${{ secrets.PACKAGE_TOKEN }}" | docker login ${{ env.REGISTRY }} -u "${{ secrets.REGISTRY_USERNAME }}" --password-stdin
      - name: Get Git Tag
        id: git_tag
        run: |
          TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          echo "tag=$TAG" >> $GITHUB_OUTPUT
      - name: Build Docker image
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest .
          docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.git_tag.outputs.tag }} .
      - name: Push Docker image
        run: |
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.git_tag.outputs.tag }}
