on: 
  push:
    tags:
      - test-*
jobs:
  build:
    runs-on: docker
    steps:
      - name: Install Docker CLI
        run: |
          apt-get update
          apt-get install -y docker.io
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: forgejo.kalmonipa.net
          username: Kalmonipa
          password: ${{ secrets.FORGEJO_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: forgejo.kalmonipa.net/kalmonipa/arty:${{ env.GITHUB_REF_NAME }}}
